### ISSUE TITLE
Using simple interpolation instead

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [ailiop/idvf#2]
- [ ] Can you explain why simple interpolation is not sufficient? 

For instance I created a spatially varying displacement vector field __u(x)__ the coordinates in the deformed configuration are then __x2=x+u(x)__. The perfect inverse mapping defined at the coordinates __x2__ is then simply -__u(x)__. Next if we need to know this inverse mapping at the reference coordinates __x__ interpolation can be used. In one test I used the MATLAB interpolation function `scatteredInterpolant`(which can be used for non-gridded data in ND), with the method set to `natural`. Interpolation objects are created for coordinate each component, so for 3D data this gives: 
```matlab
U_inverse_X2=-U; %Inverse mapping at X2

%Create interpolation functions
interFunc1_U_inverse_at_X2=scatteredInterpolant(X2,U_inverse_X2(:,1),'natural'); %X-coordinate
interFunc2_U_inverse_at_X2=scatteredInterpolant(X2,U_inverse_X2(:,2),'natural'); %Y-coordinate
interFunc3_U_inverse_at_X2=scatteredInterpolant(X2,U_inverse_X2(:,3),'natural'); %Z-coordinate

%Evaluate interpolation functions at X
U_inverse_X(:,1)=interFunc1_U_inverse_at_X2(X); %X-coordinate
U_inverse_X(:,2)=interFunc2_U_inverse_at_X2(X); %Y-coordinate
U_inverse_X(:,3)=interFunc3_U_inverse_at_X2(X); %Z-coordinate

```
If I use this approach to push back the coordinates __X2__ to the initial state to obtain __X'__ (which requires another interpolation to sample the inverse mapping back onto __X2__) I found that the error with respect to the true __X__ is very small. Why is it then that your work proposes much more advanced methods? Obviously the interpolation I use (here natural interpolation which is based on Voronoi tesselation) is "free" from continuum mechanical/elastic constraints (such as constraints on strains or volume change). However one may incorporate other interpolation methods which do have such constrains if desired. I suppose the interpolation based approach functions best for regular deformations (i.e. without regional element inversion, holes, cuts, sliding interfaces).  

Perhaps consider adding an explanation to the description and the paper to state why advanced methods are required. 

Let me know if you want me to send you the test script I created.

**Comment by ailiop** [comment]
Indeed, scattered interpolation, which is based on the reference IC condition, has been used as a heuristic for approximate DVF inversion.  It has generally been replaced by better heuristic methods in clinical applications which demand higher accuracy and efficiency.  Such methods are invariably iterative.  Moreover, there exist advanced but complicated registration algorithms that render both a forward and inverse DVF simultaneously.  Such algorithms, however, are too time consuming for time-critical applications.

Regarding the utility of idvf and our inversion framework, we may further clarify: (i) To our knowledge, the inversion algorithms underlying idvf are the first ones with theoretical guarantees for convergence to the inverse DVF and for a locally quadratic convergence rate.  (ii) By our experimental assessment with clinical thoracic/abdominal 3D CT images, the adaptive bi-residual iteration schemes in idvf greatly outperform heuristic precursor methods (including scattered interpolation) in accuracy, speed, or both.  (iii) Considering a clinical image alignment context, idvf enables one to obtain an inverse-consistent DVF pair in less than twice the time taken by commercial software currently used to compute the forward DVF.  We have added some relevant comments to the README and documentation.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for the detailed answer. So typically how much better (than scatter interpolation) are these more advanced methods? Can you comment on the improvement of accuracy or computational efficiency?

**Comment by ailiop** [comment]
#### Accuracy

Natural-neighbor interpolation with Sibson's area-based interpolant, which is what `scatteredInterpolant` uses, yields linear-order precision.  In practice, errors and IC residuals with DVF inversion via natural-neighbor scattered interpolation are most prominent in regions with high local displacement variation and relatively lower density of displaced samples; e.g., around sliding-motion interfaces.

#### Efficiency

A main challenge towards efficient scattered interpolation arises from scattered memory access patterns.  Scattered accesses under-utilize modern memory cache hierarchies, resulting in slow execution.  In addition, the Delaunay triangulation employed by many scattered interpolation methods has _O(NlogN)_ time complexity.  Conversely, gridded interpolation, which is the main operation in each idvf iteration step, entails more regular stencil-like memory accesses and _O(N)_ complexity.

In our experience with large DVFs such as over thoracic CT images, the difference in execution time is dramatic.  For example, inversion of a respiratory DVF over a 512x512x126 spatial domain takes 18 hours with `scatteredInterpolant`, while the idvf iteration with adaptive control and local acceleration takes 6.5 minutes for 20 iteration steps.  These times were measured on an Intel Xeon E5-2640v4 CPU.

(It should be noted that the idvf time does not include pre-computation of the deformation Jacobian eigenvalues.  These can be computed efficiently via appropriate batch spectral solvers, or using explicit cubic root expressions.  The latter are trivial to vectorize and only take a few seconds, but can be numerically unstable---although so far we have not observed loss of accuracy with respiratory DVFs.)

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for the detailed reply!
